### ISSUE TITLE
Add Documents, Improve Wiki, Add Training Videos

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Nettacker#1]
Hello everyone,

OWASP Nettacker doesn't have any documents or wiki right now, It's best we start Developers/Users documents to make it more friendly.

I glad if anyone can help on this! (start from [wiki](https://github.com/viraintel/OWASP-Nettacker/wiki))

**Comment by Ali-Razmjoo** [comment]
Hi,

I just improved the wiki a little bit. but still, it needs really many things to add. adding training videos for users and developers would be great!

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello,

I made the first GIF demo with simple commands.  If anyone would like to help here, I'll glad to receive more videos/gif/documents.

![2018-01-19_0-45-07](https://user-images.githubusercontent.com/7676267/35123376-283d5a3e-fcb7-11e7-9b1c-92b78ed4fecc.gif)

Regards.

**Comment by Tikam02** [comment]
@Ali-Razmjoo  i would like to contribute and make a readthedocs documentation and wiki pages for Nettacker.

**Comment by Ali-Razmjoo** [comment]
Hello,

Probably I should work on them to write the first version of documents, after that, you may contribute for corrections, update, video tutorials and etc.

Best Regards.

**Comment by ThorodanBrom** [comment]
@Ali-Razmjoo what have you used to make the GIFs? I was going to try it our myself, and am thinking of using [https://asciinema.org/](url)

**Comment by Tikam02** [comment]
If using kali Linux there is already a built-in video recording plugin, and ubuntu also has lots of video and gif creators apps.

**Comment by Ali-Razmjoo** [comment]
Hello,

@ThorodanBrom asciinema is also a great thing for making tutorials. I made them with snagit on windows. there are several tools for any OS. let me know if you need more information, just share us more details.

@Tikam02 thank you for guides

Regards.

**Comment by Ali-Razmjoo** [comment]
Hey, thanks to @pradeepjairamani 

new gif - api usage.
![output_pmq3sj](https://user-images.githubusercontent.com/7676267/39006688-118f7f0c-4419-11e8-874a-c417f0bd9081.gif)

regards.

**Comment by pradeepjairamani** [comment]
![webp net-gifmaker 1](https://user-images.githubusercontent.com/24669027/39022564-bf96bde2-4453-11e8-9814-c30db364aa4d.gif)

New giif - Wizard usage

**Comment by Ali-Razmjoo** [comment]
Hey @Tikam02,

The [wiki](https://github.com/zdresearch/OWASP-Nettacker/wiki) is almost done, let me know if you would like to work on readthedocs.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello,

I've updated the [wiki](https://github.com/zdresearch/OWASP-Nettacker/wiki), feel free to contribute and send your feedbacks.

Best Regards.

**Comment by Tikam02** [comment]
Yeah, sure wiki page looks great.I'll contribute if I get any new ideas or get any new challenge while using it.

**Comment by cwcromwell** [comment]
I'd like to contribute to the documentation. Would anyone mind if I edited the wiki? I could perform a line edit for spelling, grammar and punctuation. And I could also look for any issues with readability and usability. 

my LinkedIn:
https://www.linkedin.com/in/clarence-cromwell-2279a614/

Thanks,
Clarence

**Comment by Ali-Razmjoo** [comment]
@cwcromwell thanks for beginning interested and helping this project, it's a pleasure and we appreciate any help. I sent you an email for farther discussion.

**Comment by psahithireddy** [comment]
Hello, 
A few links aren't redirecting correctly. For example,
1) In `Home.md`, wiki and github links aren't redirecting correctly. 
2) Issues link in `Developers.md`
3) Missing _Issue Template_ and _PR Template_  in `Developers.md`.

I edited 1 and 2 on my end, but the wiki changes aren't detected in the fork in order to submit a PR.

Thanks,
[Sahithi](sahithireddy5422@gmail.com)
