### ISSUE TITLE
Adding Automatic Code Review for new pull requests

### ISSUE THREAD

**Issue by pradeepjairamani** [zdresearch/OWASP-Nettacker#106]
Codacy is an automated code review tool that helps developers save time in code reviews, Codacy can be added to this project along with Travis CI in order to make this project better.

https://app.codacy.com

Best Regards

**Comment by Ali-Razmjoo** [comment]
Hey, I've created the account and cloned the project https://app.codacy.com/app/Ali-Razmjoo/OWASP-Nettacker/dashboard

let me see how it works. is there anything else I need to do?

Regards.

**Comment by Ali-Razmjoo** [comment]
update: I've added the slack integration too.

regards.

**Comment by pradeepjairamani** [comment]
codacy has been installed successfully and I am closing this issue.

Best Regards
