### ISSUE TITLE
sender_policy_scan is not available

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Nettacker#130]
Hey,

It seems this module has a few errors in some systems. Should be checked later.

```
[X] this module "sender_policy_scan" is not available
```

Regards.
_________________
**OS**: `CentOSx`

**OS Version**: `6.5`

**Python Version**: `3.4.5`

**Comment by pradeepjairamani** [comment]
Hello,

I think the module is working fine but we have to add a same code like this for Pydns and Py3dns which I have done in setup.py file.

` if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install pyDNS; else pip install py3DNS; fi `

https://github.com/zdresearch/OWASP-Nettacker/blob/3198a5e27635f029238f234da9ed263a37bd15d6/.travis.yml#L26

Best Regards

**Comment by Ali-Razmjoo** [comment]
should we separate `requirements_py2.txt` and `requirements_py3.txt`? it's odd! any idea?

**Comment by pradeepjairamani** [comment]
good idea but that will make things more complicated.

**Comment by pradeepjairamani** [comment]
Hello,

I found a solution for this https://stackoverflow.com/questions/19559247/requirements-txt-depending-on-python-version
I will edit the requirements.txt and send the PR.

Best Regards

**Comment by Ali-Razmjoo** [comment]
oh great! I was not aware of this!

**Comment by pradeepjairamani** [comment]
Issue fixed

Best Regards
