### ISSUE TITLE
Use introjs to create a tutorial for the web API view

### ISSUE THREAD

**Issue by shaddygarg** [zdresearch/OWASP-Nettacker#132]
[IntroJS](https://introjs.com/) is a library used to create awesome tutorial generally when the user opens the site for the first time. In our case, we can have the tutorial tab specifically made in the web view or the tutorial could be deployed on a demo website. Please let me know if you have any other ideas.

**Comment by Ali-Razmjoo** [comment]
I'm on the fence, your choice!

**Comment by pradeepjairamani** [comment]
A button will be a better option.

**Comment by cwcromwell** [comment]
Buttons for functionality/behavior. Links to download or view resources.

**Comment by shaddygarg** [comment]
I have gone with the button as I think it is more suited there. Please check the PR #166. And let me know if you want any changes.

**Comment by Ali-Razmjoo** [comment]
thanks, done!
