### ISSUE TITLE
Add SSL Support for API/WebUI

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Nettacker#133]
Hey,

I think we can add SSL (HTTPS) for our API service as an optional feature, They can add their own keys/certs and also we can generate one for them, Flask is already supporting SSL.

* [Flask](http://flask.pocoo.org/snippets/111/)
* [Generate SSL Cert with Python](https://gist.github.com/ril3y/1165038)

Regards.

**Comment by aman566** [comment]
Hello Sir, I would like to start working on this issue. As a Gsoc enthusiast I would like to start my contribution with this issue. Please assign this issue to me.

**Comment by Ali-Razmjoo** [comment]
@aman566 thanks 👍 you are welcome to contribute on any of issues/features.

**Comment by aman566** [comment]
Hello @Ali-Razmjoo I have completed this issue.
Here is the screenshot for the implementation of SSL
![sslimplemented](https://user-images.githubusercontent.com/32503192/76677085-27a67c00-65f0-11ea-8e34-0a474171bc5b.png).

Please correct me if I did something wrong anywhere. Will be waiting for the response :)
.

**Comment by aman566** [comment]
I dunno why travis is breaking the code but when seeing the code base of the pull requests I made and running the command as:
`python nettacker.py -i google.com -m clickjacking_vuln --start-api --api-host 127.0.0.1 --api-port 9999`
will run the server over https. Will wait for help :)
