### ISSUE TITLE
Migrate the current database engine to sqlalchemy

### ISSUE THREAD

**Issue by shaddygarg** [zdresearch/OWASP-Nettacker#138]
Migrate the current database engine to sqlalchemy.
_________________
**OS**: `Ubuntu`

**OS Version**: `16.04`

**Python Version**: `2.7`

**Comment by Ali-Razmjoo** [comment]
Hey,

Thanks, for the PR, this enhancement is done, please add the documentation on the wiki.

Best Regards.
