### ISSUE TITLE
ipaddr module required showing up in start-api mode

### ISSUE THREAD

**Issue by shaddygarg** [zdresearch/OWASP-Nettacker#139]
ipaddr module required: http://code.google.com/p/ipaddr-py/ is showing up in start-api mode of nettacker.

![image](https://user-images.githubusercontent.com/21990986/39961114-d962f528-564c-11e8-8d85-5941c8382cff.png)
_________________
**OS**: `Ubuntu`

**OS Version**: `16.04`

**Python Version**: `2.7`

**Comment by Ali-Razmjoo** [comment]
Hey Shaddy, 

I think it appears recently (maybe after changing the requirements.txt), thanks for reporting. I will look up into it soon.

Regards.
