### ISSUE TITLE
InsecureRequestWarning showing up in terminal on running wordpress module scans

### ISSUE THREAD

**Issue by shaddygarg** [zdresearch/OWASP-Nettacker#141]
Either these warnings should be suppressed or removed.

![image](https://user-images.githubusercontent.com/21990986/40083079-ba3178da-58b0-11e8-9f43-7126910f78bb.png)

_________________
**OS**: `Ubuntu`

**OS Version**: `16.04`

**Python Version**: `2.7`

**Comment by Ali-Razmjoo** [comment]
Hey,

Where are they came from? please share the details.

Regards.

**Comment by pradeepjairamani** [comment]
Hello,

The issues arise because of SSL warnings in requests module, I will suppress the warnings.
@shaddygarg can you please share the website
Best Regards

**Comment by shaddygarg** [comment]
Sure, the target was www.zdresearch.com
