### ISSUE TITLE
Include Ubuntu binary dependencies in README

### ISSUE THREAD

**Issue by HuntedCodes** [zdresearch/OWASP-Nettacker#161]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Ubuntu`

**OS Version**: `16.04 - 18.04`

**Python Version**: `2 or 3`

The readme needs installation instructions for Ubuntu that include binary dependencies from `apt`.

```
sudo apt-get install libcurl4-openssl-dev libssl-dev
```

The Python development package was also needed at some point:

- Python 2: `python-dev`
- Python 3: `python3-dev`

**Comment by Ali-Razmjoo** [comment]
Hello,

thanks for this information, I've added them to the [wiki](https://github.com/zdresearch/OWASP-Nettacker/wiki/Installation#requirements). let me know if there are any more problems.

Best Regards.
