### ISSUE TITLE
failed to build ssh_brute module

### ISSUE THREAD

**Issue by zhaoyun95** [zdresearch/OWASP-Nettacker#162]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Windows 10 Enterprise`

**OS Version**: `1803`

**Python Version**: `3.6.5`
------------------------------------
python setup.py install
----------------------------------------------------
Processing OWASP_Nettacker-0.0.1-py3.6.egg
creating d:\programdata\anaconda3\lib\site-packages\OWASP_Nettacker-0.0.1-py3.6.egg
Extracting OWASP_Nettacker-0.0.1-py3.6.egg to d:\programdata\anaconda3\lib\site-packages
  File "d:\programdata\anaconda3\lib\site-packages\OWASP_Nettacker-0.0.1-py3.6.egg\lib\brute\ssh\engine.py", line 152
    print "here"
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("here")?

**Comment by Ali-Razmjoo** [comment]
Hello,

thanks for the report, this line added by accident I just deleted it. please update your repository to the veesion.

Best Regards.
