### ISSUE TITLE
I keep getting this issue after running the PMA_Scan

### ISSUE THREAD

**Issue by pradeepjairamani** [zdresearch/OWASP-Nettacker#172]
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/OWASP-Nettacker/lib/http_fuzzer/engine.py", line 312, in request_without_data
    if rule_evaluator(response, condition):
  File "/root/OWASP-Nettacker/lib/http_fuzzer/engine.py", line 337, in rule_evaluator
    return eval(condition)
  File "<string>", line 1, in <module>
AttributeError: 'int' object has no attribute 'status_code'

**Comment by Ali-Razmjoo** [comment]
can you please copy the condition in code? I believe you write that wrong, correct example: `response.status_code in [200, 401, 403]`

**Comment by pradeepjairamani** [comment]
I haven't edited the code yet.

**Comment by shaddygarg** [comment]
Can you tell me the input?

**Comment by Ali-Razmjoo** [comment]
`python nettacker.py -i 127.0.0.1 -m pma_scan`, are you working on an online target?

**Comment by pradeepjairamani** [comment]
yes, I used an online target.

**Comment by Ali-Razmjoo** [comment]
please check, I cannot figure that's the problem, but it kind of solve it for me,

**Comment by shaddygarg** [comment]
@Ali-Razmjoo, I believe this is the better option. The error occurs when the request timeouts and so checking the response whether it is a valid response will eliminate the error I think!

**Comment by Ali-Razmjoo** [comment]
thanks, fixed.
