### ISSUE TITLE
if statements

### ISSUE THREAD

**Issue by pylyf** [zdresearch/OWASP-Nettacker#177]
Hello. I want to share a way to make if statements a bit nicer, but I'm not sure whether it's worth a commit ( don't know if you like this way ) or not.

You have a code like this : 
```
if check_subdomains: 
    if check_ranges: 
        if enumerate_flag:

```

You could use:
```
if check_subdomains and check_ranges.....
```
but long lines are against POP, therefore this should work :

```
conditions = [check_ranges, 
enumerate_flag, 
check_subdomains]

if all(conditions):
   print("yay")
```

_Would like to hear your opinion. Cheers_.

**Comment by Ali-Razmjoo** [comment]
Hello,

thanks for opening this issue, the reason I used multiple "if" statement is that we have "else" statement as well, but I believe I used many wrong statements in the code, and we already created this issue in here #135 

please feel free to contribute and send your PR. I may close this issue and we can continue in #135 

Best Regards.
