### ISSUE TITLE
Create Maltego Transaction for OWASP-Nettacker (Local & Server)

### ISSUE THREAD

**Issue by ArianPH** [zdresearch/OWASP-Nettacker#19]
Hi everyone,

I want to create Maltego transaction for the framework, first, I will create a local transaction and then develop and complete that, we may start a server-based transaction in the second phase.

Let me know if you have suggestion about this.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello Arian,

Thank you for your idea, please start the first phase ( the local transaction) and let me know the details. The second phase (server-based transaction) needs its infrastructure that we don't have yet, but we will in the near future.

We welcome any contributions from developers.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello @ArianPH ,

would you please send us updates regarding this feature? I am planning for GSoC, let me know if you are working on this.

Best Regards.

**Comment by shaddygarg** [comment]
Hey @Ali-Razmjoo,
Can you please give me more information about this maltego transaction? Googling it yields no relevant results and I can only find some references of maltego transform. Is it related to https://www.paterva.com/web7/. Is this issue about visualizing the data effectively into an interactive graph module?
Regards.

**Comment by Ali-Razmjoo** [comment]
Hey,

* Is this issue about visualizing the data effectively into an interactive graph module?
yes, it is.  references: https://docs.paterva.com/en/developer-portal/tds-transforms/trx-transform-library-guide/

Regards.

**Comment by shaddygarg** [comment]
Hey @Ali-Razmjoo,
I was going through the docs and sample examples of local maltego transform. We can use two python libraries for it. One is the official [Basic Python Library](https://docs.paterva.com/en/developer-portal/tds-transforms/trx-transform-library-guide/), other is [Canari](https://github.com/redcanari/canari3), which is also mentioned on their official website. I am currently making some examples for learning and I would like to know if you had a preference regarding which one to use.
Best Regards.

**Comment by pradeepjairamani** [comment]
Hello @shaddygarg ,

Do let me know about the details of this one, I got confused with creating and transforming charts.

Best Regards

**Comment by Ali-Razmjoo** [comment]
Hi,

thanks to Shaddy's last PR, now I mark this issue as close until we get ideas for updating this section.
* docs: https://github.com/zdresearch/OWASP-Nettacker/wiki/Usage#maltego-transforms
Regards.
