### ISSUE TITLE
py3dns version support issue

### ISSUE THREAD

**Issue by V33RU** [zdresearch/OWASP-Nettacker#200]
Collecting py3DNS==3.1.1a0 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/8e/a3/b8cae77d27ac818390f864583e881ee7d332e2450391ddf1b52dcaaeb521/py3dns-3.1.1a.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dhbntdi9/py3DNS/setup.py", line 7, in <module>
        import DNS
      File "/tmp/pip-install-dhbntdi9/py3DNS/DNS/__init__.py", line 27, in <module>
        from .Base import DnsRequest
      File "/tmp/pip-install-dhbntdi9/py3DNS/DNS/Base.py", line 96
        self.async=None
                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dhbntdi9/py3DNS/

#installed version is 3.2.1 , required version not able install

**Comment by simoncaogit** [comment]
I have same issue
Collecting py3DNS==3.1.1a0 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/8e/a3/b8cae77d27ac818390f864583e881ee7d332e2450391ddf1b52dcaaeb521/py3dns-3.1.1a.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xslw1okl/py3DNS/setup.py", line 7, in <module>
        import DNS
      File "/tmp/pip-install-xslw1okl/py3DNS/DNS/__init__.py", line 27, in <module>
        from .Base import DnsRequest
      File "/tmp/pip-install-xslw1okl/py3DNS/DNS/Base.py", line 96
        self.async=None
                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xslw1okl/py3DNS/

**Comment by Ali-Razmjoo** [comment]
use docker for now until we fix the issue, thanks for reporting it.

**Comment by securestep9** [comment]
pyDNS is now bumped up to 3.2.1 which should resolve this issue

**Comment by windowshopr** [comment]
I'm having this issue as well, Python 3.7.9, Windows 10 (probably not supported, but haven't read it anywhere yet). 

Just downloaded the package today, and ran `pip install -r requirements.txt`, then tried to run `python nettacker.py --start-api` and it gives me this error:

```
...\Nettacker>python nettacker.py --start-api
←[1;31m[X] ←[1;33mpip3 install -r requirements.txt ---> py3DNS==3.2.1 not installed!←[0m
```

I followed the steps above as but same issue. Is it a Windows thing?

**Comment by iamvinny** [comment]
> I'm having this issue as well, Python 3.7.9, Windows 10 (probably not supported, but haven't read it anywhere yet).
> 
> Just downloaded the package today, and ran `pip install -r requirements.txt`, then tried to run `python nettacker.py --start-api` and it gives me this error:
> 
> ```
> ...\Nettacker>python nettacker.py --start-api
> ←[1;31m[X] ←[1;33mpip3 install -r requirements.txt ---> py3DNS==3.2.1 not installed!←[0m
> ```
> 
> I followed the steps above as but same issue. Is it a Windows thing?

Same issue on MacOS

**Comment by V33RU** [comment]
yes in docker everything working fine , i am using same ..

**Comment by securestep9** [comment]
> > I'm having this issue as well, Python 3.7.9, Windows 10 (probably not supported, but haven't read it anywhere yet).
> > Just downloaded the package today, and ran `pip install -r requirements.txt`, then tried to run `python nettacker.py --start-api` and it gives me this error:
> > ```
> > ...\Nettacker>python nettacker.py --start-api
> > ←[1;31m[X] ←[1;33mpip3 install -r requirements.txt ---> py3DNS==3.2.1 not installed!←[0m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I followed the steps above as but same issue. Is it a Windows thing?
> 
> Same issue on MacOS

Use **Python 3.11** not 3.7.9
