### ISSUE TITLE
subdomain scan returning items with '<BR>' 

### ISSUE THREAD

**Issue by securestep9** [zdresearch/OWASP-Nettacker#202]
subdomain scan has recently started returning subdomains with 'BR' HTML tag like this:

`lists.owasp.org<BR>www.lists.owasp.org `

**Comment by securestep9** [comment]
This is due to crt.sh listing SNI domains in one table row separated by `<BR>`

**Comment by shaddygarg** [comment]
Hey @securestep9, should I take up this issue or is anyone working on it? It possibly will be a matter of changing the parsing.

**Comment by shaddygarg** [comment]
Issue resolved, waiting for review.

**Comment by securestep9** [comment]
thank you @shaddygarg ,pull request  merged, issue closed
