### ISSUE TITLE
[Low] Circular Dependency Import Issue

### ISSUE THREAD

**Issue by 0xInfection** [zdresearch/OWASP-Nettacker#237]
There is an import-based circular dependency/variable name collision between the files `core/attack.py` and `core/compatible.py`.

The file `core/compatible.py` contains the following on line 6:
```
from core.alert import *
```
And the code in `core/alert.py` contains the following on line 8:
```
from core.compatible import version
```
So as you clearly see there is a circular import which is causing variable name collisions between the 2 files.

Issue fixed by: #238
_________________
**OS**: `Ubuntu`

**OS Version**: `18.04`

**Python Version**: `3.6`

**Comment by beyondexp** [comment]
The file core/compatible.py contains the following on line 27:
` from core.alert import write_to_api_console`
Circular import in Python can be avoided by introducing them into functions, but this is cure the symptoms, not the disease。

**Comment by 0xInfection** [comment]
Hey @beyondexp,

I think you are mistaken somewhere. If you look at the [changes proposed](https://github.com/zdresearch/OWASP-Nettacker/pull/238/files) via #238, you'll see I removed all dependents from `core/alert.py`. The only logic here was that `core/compatible.py` may depend on `core/alert.py` but the reverse should not be true, i.e. `core/alert.py` shouldn't depend on `core/compatible.py` since it itself is a top level import.

**Comment by beyondexp** [comment]
Sorry i didn't see your this commit [0c62662](https://github.com/zdresearch/OWASP-Nettacker/pull/238/commits/0c626625bcbf5f48fcee3c042f133fb26fec94ac)
