### ISSUE TITLE
CSV result export feature 

### ISSUE THREAD

**Issue by securestep9** [zdresearch/OWASP-Nettacker#250]
Currently Nettacker is only capable of producing results in JSON,TXT and HTML format A new feature to produce results in CSV format is needed

Command line option -o  :

 `-o results.csv
`

**Comment by aman566** [comment]
I tried to fix it and it is working. I ran
`python nettacker.py -m clickjacking_vuln -i https://pintasuper.com -o results.csv` and it gave the output:

![image](https://user-images.githubusercontent.com/32503192/81729875-58007e80-94aa-11ea-8a54-673dcac75bbc.png)

@securestep9 please review it :)
