### ISSUE TITLE
Description column in the output not changes

### ISSUE THREAD

**Issue by aman566** [zdresearch/OWASP-Nettacker#252]
The Description column in the output of any vulnerability scan does not change its width. Due to this, the output cannot be in a readable form. So the width of the description column should change.

![image](https://user-images.githubusercontent.com/32503192/80377018-49b24000-88b8-11ea-90d6-63796af18244.png)

_________________
**OS**: `Linux`

**OS Version**: `Ubuntu`

**Python Version**: `3.x`

**Comment by securestep9** [comment]
Hi @aman566 the standard terminal output is 80 bytes long. Text output is there for information only to warn the user that there are findings, it is assumed that HTML/JSON (and hopefully CSV) will be used for actual 'consumption' of findings
