### ISSUE TITLE
The pma_scan module breaks

### ISSUE THREAD

**Issue by aman566** [zdresearch/OWASP-Nettacker#266]
The pma_scan module is broken and gives error when run.

![image](https://user-images.githubusercontent.com/32503192/81449683-685ce480-919e-11ea-992f-86965262b753.png)

Code is breaking somewhere in start()

![image](https://user-images.githubusercontent.com/32503192/81449542-15832d00-919e-11ea-89c7-37c3a9fb04e9.png)

Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux`

**OS Version**: `Ubuntu 18.04`

**Python Version**: `3.6.9`

**Comment by securestep9** [comment]
this  bug is happening Python3 only. Python2 version works
