### ISSUE TITLE
Wizard not working

### ISSUE THREAD

**Issue by aman566** [zdresearch/OWASP-Nettacker#295]
![ezgif-2-fadd3d897e4f](https://user-images.githubusercontent.com/32503192/84558626-ec802a00-ad51-11ea-9df2-72b0ba5a1212.gif)

Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux`

**OS Version**: `Ubuntu 18.04`

**Python Version**: `3.6.9`

**Comment by securestep9** [comment]
looks like this bug was introduced after API SSL commit..
