### ISSUE TITLE
This project isn't shown in https://owasp.org/projects

### ISSUE THREAD

**Issue by q2dg** [zdresearch/OWASP-Nettacker#321]
So its visibility can be very small.
I think you should talk with someone of OWASP website staff.
Thanks

**Comment by aman566** [comment]
Hello @q2dg It is available :-)
Just navigate to the "Type" tab:
![image](https://user-images.githubusercontent.com/32503192/87879050-d2e39980-ca05-11ea-84a1-eef24a55a903.png)

![image](https://user-images.githubusercontent.com/32503192/87879042-c6f7d780-ca05-11ea-918f-20bb3b668ee7.png)

**Comment by q2dg** [comment]
Oooh, it's true, you're right. But in "Level" tab it isn't. 
A bit messy, don't you think?
