### ISSUE TITLE
smtp brute tls issue

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Nettacker#326]
I noticed we used `starttls()` for smtp brute, it won't work on normal smtp unless tls is enabled. 

https://github.com/zdresearch/OWASP-Nettacker/blob/master/lib/brute/smtp/engine.py#L62
https://github.com/zdresearch/OWASP-Nettacker/blob/master/lib/brute/smtp/engine.py#L122

we can remove these to lines and have another module (smtps_brute) instead for smtp+tls/ssl or maybe we can add a condition to detect if it should use tls or not?

**Comment by securestep9** [comment]
There should be a way to check if SMTP requires TLS as the response from the initial EHLO will contain 250-STARTTLS. I don't think we need two modules - we should be able to detect if there is no STARTTLS support. @aman566 - can you please investigate / fix?

**Comment by aman566** [comment]
yes I am working on it and will keep you updated :)

**Comment by securestep9** [comment]
@Ali-Razmjoo starttls PR fix merged

**Comment by Ali-Razmjoo** [comment]
Great thanks.
