### ISSUE TITLE
Create GUI Based on the API

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Nettacker#6]
Hello everyone,

After completing the API, It's best to add create a GUI for the project. Right now I am thinking about Qt but let me know if you have a better idea.

Let me know if there is any question.
Regards.

**Comment by Tikam02** [comment]
@Ali-Razmjoo  Integrating Nettacker with Django will be best.Django for GUI, fast database and reports like HTML report or xml reports.And in the back Nettacker will be processing.

**Comment by Ali-Razmjoo** [comment]
Hello @Tikam02,

I already have gone with flask, and API is almost working, use `--start-api` to check it up.

Regards.
