### ISSUE TITLE
Error in threading (python 3.4, 3.5)

### ISSUE THREAD

**Issue by pradeepjairamani** [zdresearch/OWASP-Nettacker#94]
Error Fetched from Travis CI
_________________
"os": "linux",

**Python Version**: "3.4","3.5"

![screenshot_9](https://user-images.githubusercontent.com/24669027/37872955-db6b34f4-302f-11e8-8744-072731302c9f.png)
![screenshot_10](https://user-images.githubusercontent.com/24669027/37872956-dbb4ed7e-302f-11e8-8187-b6d91be54176.png)

**Comment by pradeepjairamani** [comment]
data = json.dumps(
                    {'HOST': host, 'USERNAME': '', 'PASSWORD': '', 'PORT': port, 'TYPE': 'port_scan',
                     'DESCRIPTION': messages(language, "port/type").format(port, "STEALTH"), 'TIME': now(),
                     'CATEGORY': "scan", 'SCAN_ID': scan_id,
                     'SCAN_CMD': scan_cmd}) + '\n'
                __log_into_file(log_in_file, 'a', data, language)
                __log_into_file(thread_tmp_filename, 'w', '0', language)


This message needs to be encoded

json.loads(myResponse.content.decode('utf-8'))

References: https://stackoverflow.com/questions/42683478/typeerror-the-json-object-must-be-str-not-bytes/42683509

**Comment by Ali-Razmjoo** [comment]
Bug fixed and closed.
