### ISSUE TITLE
Specific CMS Scanner

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Nettacker#98]
Hey,

for the next levels of the modules and more complicated, we may start to bring CMS scanners into the OWASP Nettacker, OWASP already has a few (like [vbscan](https://github.com/rezasp/vbscan), [joomscan](https://github.com/rezasp/joomscan)) and we can start implementing from there.

I glad if anyone could help on this.

Regards.

**Comment by pradeepjairamani** [comment]
Ok i will start on wordpress and drupal then.
Firstly I will check what cms is running on that site and according to that I will start the scanning.
Vb and joomscan will also be implemented.

Best Regards

**Comment by mzfr** [comment]
@Ali-Razmjoo This issue is fixed right?
